data_collection_name: "MultiplEYE_SQ_CH_Zurich_1_2025"

# pick either include or exclude sessions, if none is specified, all sessions are included
include_sessions:
  - 006_SQ_CH_1_ET1


exclude_sessions:

include_pilots: True

# Hardware settings
expected_sampling_rate_hz: 1000  # Hz


# NOT YET IN USE; IGNORE. if any sessions do not use the standard stimulus version, specify so here
session_to_stimuli:
  - "session":

default_stimulus_version:
